Repository jenkinsci/stapler-maven-plugin, pull requests merged in 2022-08, with the labels that each got.

#4 refactor: Make it build in 2022
  .cvsignore
  .gitignore
  Jenkinsfile
  pom.xml
  src/test/java/org/kohsuke/stapler/DummyTest.java
Labels: chore

#5 chore: Add release drafter & dependabot
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  README.md
Labels: chore

#6 Incrementalify plugin
  .gitignore
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
  src/main/java/org/kohsuke/stapler/L10nProgress.java
  src/main/java/org/kohsuke/stapler/LocalizerMojo.java
  src/main/java/org/kohsuke/stapler/LocalizerMojo2.java
  src/main/java/org/kohsuke/stapler/LocalizerProgressMojo.java
  src/main/java/org/kohsuke/stapler/Properties.java
  src/main/java/org/kohsuke/stapler/TaglibDocMojo.java
Labels: enhancement

#10 Migrate `localRepository` to Maven annotation
  src/main/java/org/kohsuke/stapler/TaglibDocMojo.java
Labels: skip-changelog

#9 ci: Test on Java 17
  Jenkinsfile
Labels: chore

#11 Facelift & cleanup
  src/main/java/org/kohsuke/stapler/L10nProgress.java
  src/main/java/org/kohsuke/stapler/LocalizerMojo.java
  src/main/java/org/kohsuke/stapler/LocalizerProgressMojo.java
  src/main/java/org/kohsuke/stapler/Properties.java
  src/main/java/org/kohsuke/stapler/TaglibDocMojo.java
Labels: chore

#12 Update dom4j from 1.6.1 to 2.1.3
  pom.xml
  src/main/java/org/kohsuke/stapler/TaglibDocMojo.java
Labels: dependencies, java

#14 Use `String#join` where possible
  src/main/java/org/kohsuke/stapler/TaglibDocMojo.java
Labels: skip-changelog

#13 Maven 3 upgrade
  pom.xml
  src/main/java/org/kohsuke/stapler/TaglibDocMojo.java
Labels: dependencies, java

#17 Ignore Atlassian version of Jaxen
  .github/dependabot.yml
Labels: skip-changelog
